---
name: PHPStan analysis
on:
    push: ~
    pull_request: ~

jobs:
    phpstan:
        name: PHPStan analysis tests on ${{ matrix.php }} ${{ matrix.composer-flags }}
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php: [ '8.1', '8.2', '8.3' ]
                composer-flags: [ '' ]
        steps:
            - uses: actions/checkout@v2
            - uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  tools: composer:v2
            - run: composer update --no-progress ${{ matrix.composer-flags }}
            - run: vendor/bin/phpstan
